<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PixDynamicGallery.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Persistence -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <!-- Cloud storage providers -->
    <PackageReference Include="AWSSDK.S3" Version="3.7.408" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.23.0" />

    <!-- FileSystemWatcher background service host -->
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixDynamicGallery.Application\PixDynamicGallery.Application.csproj" />
  </ItemGroup>

</Project>
